<a href="https://colab.research.google.com/github/YashitaaArya/Python-Practices/blob/main/EncodingCategoricalData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('/content/customer.csv')

In [6]:
df.sample(5)

    age  gender   review education purchased
46   64  Female     Poor        PG        No
24   16  Female  Average        PG       Yes
38   45  Female     Good    School        No
18   19    Male     Good    School        No
0    30  Female  Average    School        No

All columns are categorical and i need to transform each into numerical.
1. Gender -> One-Hot-Encoder
2. Review, Education -> Ordinal-Encoder
3. Purchased -> Label-Encoder

In [7]:
df=df.iloc[:,2:]

In [8]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

whenever we do transformation, we move ahead with train-test split

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [10]:
x_train

     review education
38     Good    School
39     Poor        PG
29  Average        UG
25     Good    School
6      Good    School
42     Good        PG
24  Average        PG
10     Good        UG
46     Poor        PG
22     Poor        PG
37  Average        PG
8   Average        UG
43     Poor        PG
7      Poor    School
12     Poor    School
19     Poor        PG
5   Average    School
32  Average        UG
16     Poor        UG
47     Good        PG
21  Average        PG
36     Good        UG
3      Good        PG
41     Good        PG
44  Average        UG
23     Good    School
26     Poor        PG
28     Poor    School
34  Average    School
9      Good        UG
15     Poor        UG
45     Poor        PG
48     Good        UG
49     Good        UG
4   Average        UG
33     Good        PG
0   Average    School
14     Poor        PG
11     Good        UG
40     Good    School

# Ordinal Encoding

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
# order giving for the ordinal data

In [13]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [15]:
x_train

array([[2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

label encoding should be used only and only (explicitly) when working on 0s or 1s of output column.

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
le.fit(y_train)

LabelEncoder()

In [20]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [21]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [22]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])

# One-Hot Encoding

In [23]:
df2=pd.read_csv('/content/cars.csv')

In [24]:
df2.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [25]:
df2['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [27]:
df2['brand'].nunique()

32

In [28]:
df2['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

OneHotEncoding using Pandas

In [29]:
pd.get_dummies(df2,columns=['fuel','owner']) # fuel col will be removed and added 4

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

K-1 OneHotEncoding

In [30]:
pd.get_dummies(df2,columns=['fuel','owner'],drop_first=True)
# pehla column hat jaata hai

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

OneHotEncoding using sklearn

In [32]:
# first we split data into train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df2.iloc[:,0:4],df2.iloc[:,-1],test_size=0.2)
#1st 4 cols in input, last col in output

In [34]:
X_train

           brand  km_driven    fuel         owner
4249         BMW       8500  Diesel   First Owner
1007      Toyota     114368  Diesel  Second Owner
908      Hyundai      32000  Petrol   First Owner
1422      Maruti      90000  Diesel  Second Owner
5286       Honda      30000  Diesel   First Owner
...          ...        ...     ...           ...
2991        Tata      25000  Petrol   First Owner
1412      Toyota     155000  Diesel   Third Owner
5651    Mahindra     120000  Diesel  Second Owner
704     Mahindra      40000  Diesel  Second Owner
7072  Volkswagen      75000  Diesel   First Owner

[6502 rows x 4 columns]

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
ohe=OneHotEncoder(sparse_output=False)

In [45]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
# X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new=ohe.transform(X_test[['fuel','owner']])
# X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()
## produces a sparse matrix

In [46]:
X_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [47]:
X_train[['brand', 'km_driven']].values

array([['BMW', 8500],
       ['Toyota', 114368],
       ['Hyundai', 32000],
       ...,
       ['Mahindra', 120000],
       ['Mahindra', 40000],
       ['Volkswagen', 75000]], dtype=object)

In [48]:
# both numpy array need to be stacked horizontally
np.hstack((X_train[['brand', 'km_driven']].values,X_train_new)).shape

(6502, 11)

OneHotEncoding with Top Categories

In [50]:
df2['brand'].value_counts()
# taking threshold=100 and rest=other

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [51]:
counts=df2['brand'].value_counts()

In [52]:
df2['brand'].nunique()
threshold=100

In [53]:
counts[counts<=threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [54]:
replaccce=counts[counts<=threshold].index

In [58]:
pd.get_dummies(df2['brand'].replace(replaccce,'others')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
3082,False,False,False,False,False,False,False,False,False,False,False,False,True
4357,False,False,False,False,False,False,False,False,False,False,False,True,False
73,False,False,False,False,True,False,False,False,False,False,False,False,False
373,False,False,False,False,False,False,False,False,False,True,False,False,False
7010,False,False,False,False,False,False,True,False,False,False,False,False,False